name: pod_debounce
description: A tool to debounce a UI event callback.
version: 0.0.1
# homepage: https://www.example.com
environment:
  sdk: ">=2.18.6 <3.0.0"
dependencies:
  riverpod: ^2.1.3
dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.1
  very_good_analysis: ^3.1.0
